Repository razorpay/hypertrace-ui, pull requests merged in 2022-05, with the labels that each got.

#36 Load `email` and `name` for analytics purpose from `user-info` endpoint for HyperTrace
  conf/default.conf
  projects/common/src/telemetry/providers/rudderstack/rudderstack-provider.ts
Labels: enhancement

#32 feat: save Explorer queries to localStorage
  package-lock.json
  projects/assets-library/src/icons/icon-type.ts
  projects/common/src/constants/application-constants.ts
  projects/observability/src/pages/explorer/explorer.component.scss
  projects/observability/src/pages/explorer/explorer.component.test.ts
  projects/observability/src/pages/explorer/explorer.component.ts
  projects/observability/src/pages/explorer/explorer.module.ts
  src/app/shared/feature-resolver/feature-resolver.service.ts
Labels: ReadyForReview

#38 Hyperdash models update
  projects/observability/src/shared/dashboard/data/graphql/filter/graphql-key-value-filter.model.ts
  projects/observability/src/shared/dashboard/data/graphql/metric-aggregation/metric-aggregation-data-source.model.ts
  projects/observability/src/shared/dashboard/data/graphql/specifiers/explore-selection-specification.model.ts
  projects/observability/src/shared/dashboard/data/graphql/table/explore/explore-table-data-source.model.test.ts
  projects/observability/src/shared/dashboard/data/graphql/table/explore/explore-table-data-source.model.ts
  projects/observability/src/shared/graphql/request/builders/specification/explore/explore-specification-builder.ts
Labels: ReadyForReview, bug

#35 feat: add saved queries as a nav item to sidebar
  projects/components/src/navigation/navigation-list.constants.ts
  projects/components/src/navigation/navigation-list.service.ts
  projects/observability/src/pages/explorer/explorer-service.ts
  projects/observability/src/pages/explorer/explorer.component.scss
  projects/observability/src/pages/explorer/explorer.component.test.ts
  projects/observability/src/pages/explorer/explorer.component.ts
  projects/observability/src/pages/saved-queries/saved-queries.component.scss
  projects/observability/src/pages/saved-queries/saved-queries.component.test.ts
  projects/observability/src/pages/saved-queries/saved-queries.component.ts
  projects/observability/src/pages/saved-queries/saved-queries.module.ts
  projects/observability/src/public-api.ts
  src/app/routes/root-routing.module.ts
  src/app/routes/saved-queries/saved-queries-routing.module.ts
  src/app/shared/navigation/navigation.component.test.ts
  src/app/shared/navigation/navigation.component.ts
Labels: ReadyForReview, enhancement
