Repository razorpay/hypertrace-ui, pull requests merged in 2022-09, with the labels that each got.

#80 feat: add QoI tab foundation code
  projects/common/src/constants/application-constants.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.module.ts
  projects/observability/src/pages/apis/service-detail/service-detail.component.test.ts
  projects/observability/src/pages/apis/service-detail/service-detail.component.ts
  projects/observability/src/pages/apis/service-detail/service-detail.module.ts
  projects/observability/src/public-api.ts
  src/app/routes/services/service-detail/service-detail-routing.module.ts
  src/app/shared/feature-resolver/feature-resolver.service.ts
Labels: ReadyForReview

#82 feat [QoI]: Add static UI for total score
  projects/components/src/progress-circle/progress-circle.component.scss
  projects/components/src/progress-circle/progress-circle.component.ts
  projects/components/src/progress-circle/progress-circle.module.ts
  projects/components/src/public-api.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/category-card.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/index.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/org-score.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/org-score.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/total-score.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/total-score.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.fixture.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.module.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.service.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.types.ts
Labels: ReadyForReview

#81 Deployment Markers - Set up tab, routes and feature flag integration
  projects/assets-library/assets/json/config.json
  projects/common/src/constants/application-constants.ts
  projects/components/src/breadcrumbs/breadcrumbs.service.test.ts
  projects/components/src/breadcrumbs/breadcrumbs.service.ts
  projects/components/src/tabs/navigable/navigable-tab.ts
  projects/observability/src/pages/apis/service-detail/deployments/service-deployments.component.scss
  projects/observability/src/pages/apis/service-detail/deployments/service-deployments.component.ts
  projects/observability/src/pages/apis/service-detail/deployments/service-deployments.module.ts
  projects/observability/src/pages/apis/service-detail/service-detail.component.test.ts
  projects/observability/src/pages/apis/service-detail/service-detail.component.ts
  projects/observability/src/pages/apis/service-detail/service-detail.module.ts
  projects/observability/src/public-api.ts
  src/app/routes/services/service-detail/service-detail-routing.module.ts
  src/app/shared/feature-resolver/feature-resolver.service.ts
Labels: ReadyForReview, enhancement

#85 Fixes the `edit` functionality for `panel` in custom dashboards
  projects/observability/src/pages/custom-dashboards/custom-dashboard-panel-edit/custom-dashboard-panel-edit.component.ts
Labels: ReadyForReview

#86 feat: add qoi children routes
  projects/observability/src/pages/apis/service-detail/instrumentation/components/category-card.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/category-details.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/index.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-details.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-details.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-overview.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-overview.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.module.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.service.ts
  projects/observability/src/public-api.ts
  src/app/routes/services/service-detail/service-detail-routing.module.ts
Labels: DoNotReview

#84 feat [QoI]: add category cards and routing
  projects/components/src/button/button.component.ts
  projects/components/src/button/button.ts
  projects/components/src/progress-bar/progress-bar.component.scss
  projects/components/src/progress-bar/progress-bar.component.ts
  projects/components/src/progress-bar/progress-bar.module.ts
  projects/components/src/public-api.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/category-card.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/category-card.component.test.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/category-card.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/index.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-details.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-details.component.test.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-details.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-overview.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-overview.component.test.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/instrumentation-overview.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/components/progress-bar.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/components/progress-bar.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.scss
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.test.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.component.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.fixture.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.module.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.service.ts
  projects/observability/src/pages/apis/service-detail/instrumentation/service-instrumentation.types.ts
  projects/observability/src/public-api.ts
  src/app/routes/services/service-detail/service-detail-routing.module.ts
Labels: ReadyForReview
